### PR TITLE
Adding openjdk 7.0.161(zulu 7.20.0.3)

### PR DESCRIPTION
**Pull request by karl616**
In fact, this is a downgrade, but I would appreciate to have this legacy version included.

### CODE REVIEW

**Comment by karl616** [comment]
@johanneskoester 

Would you have time to have a look at this PR? It would allow me to remove my java-jdk dependency in my bioconda recipe. It didn't pass the checks earlier, but I think I have corrected the mistakes. Still, this is all kind of new to me... What would be the normal procedure? just wait?

**Comment by bgruening** [comment]
@karl616 can you please target a new branch. For example a `7.0` branch and not master. Master should container the latest version and we can maintain older version in extra branches.

**Comment by karl616** [comment]
@bgruening That makes sense. My problem is that I have no rights here at all. Can I request rights somehow?

**Comment by sodre** [comment]
I created the 7.x series branch. I'll take care of merging your changes.

**Comment by bgruening** [comment]
Thanks @sodre

**Comment by sodre** [comment]
Merged into 7.x branch d622690d6341df95323984e53005086e96b0b42f

**Comment by karl616** [comment]
Thanks to both of you!

**Pull request closed without merging**
