### PR TITLE
openjdk v23.0.1

### PR DESCRIPTION
**Pull request by h-vetinari**

### CODE REVIEW

**Comment by XhstormR** [comment]
ping

**Comment by h-vetinari** [comment]
There's nothing to ping here - this is currently not working and I don't have time to debut it ATM.

If you want jdk 23, check out this branch, add some fixes on top and open a new PR. I'll happily merge it once it's green.

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Review by h-vetinari — COMMENTED** [review]
LGTM, thanks a lot!

**Pull request merged**
