### PR TITLE
Zulu OpenJDK-1.8.144

### PR DESCRIPTION
**Pull request by abhi18av**
Working on a fresh fork and patch.

### CODE REVIEW

**Comment by abhi18av** [comment]
Hey, have I done something wrong that the travis build is taking so long to even trigger? Please let me know how to find the solution.

**Comment by sodre** [comment]
I don't think so. It is just queued...

**Comment by abhi18av** [comment]
@sodre Hey, so all CI checks have passed.

**Comment by abhi18av** [comment]
Thanks :+1:

**Pull request merged**
