### PR TITLE
make activate script compatible with zsh

### LINKED ISSUE #22: syntax error in activation script for zsh
https://github.com/conda-forge/openjdk-feedstock/blob/01efaec1ac9eea803011181e588796cf412cd308/recipe/scripts/activate.sh#L7

weirdly, this if statement line does not seem to be valid code for zsh:

getting 
```bash
/home/croth1/miniconda2/envs/PARpipe/etc/conda/activate.d/java_home.sh:7: = not found
```

### PR DESCRIPTION
**Pull request by croth1**
should fix #22

### CODE REVIEW

**Comment by croth1** [comment]
@conda-forge-admin, please rerender

**Comment by croth1** [comment]
@conda-forge/core - can anybody help me understanding what the linter problem is?

**Comment by scopatz** [comment]
Might be a bug in the linter

**Comment by jakirkham** [comment]
If you think there is a linter issue, please raise over at `conda-smithy`. Thanks.

**Comment by isuruf** [comment]
`rpath` in meta.yaml should be `rpaths`

**Comment by sodre** [comment]
Actually, it might explain why I needed to add settings for LD_LIBRARY_PATH when integrating with r-rjava. 

I agree with @jakirkham, remove it for now and open a new issue to look into the rpaths settings.

**Comment by croth1** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
