### PR TITLE
Build from source on linux

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes https://github.com/conda-forge/openjdk-feedstock/issues/59

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by hadim** [comment]
This PR is mixing Zulu builds and custom compiled Java from another source on Linux. I am concern about the possible downstream impacts of this. @ctrueden any thoughts?

**Comment by hadim** [comment]
That being said we coule switch from Zulu to AdoptOpenJDK binaries for OSX, Linux and windows.

**Comment by isuruf** [comment]
> This PR is mixing Zulu builds and custom compiled Java from another source on Linux.

The source is the same for both. I've used AdoptOpenJDK source because they provide source tarball as a single tarball instead of separate tarballs.
On linux, Zulu builds are still used for bootstrapping the JDK build.

> That being said we coule switch from Zulu to AdoptOpenJDK binaries for OSX, Linux and windows.

Why? I'm building this from source to prevent vendoring libraries like `libfreetype.so` so that `openjdk` and `freetype` can be co-installable without clobbering

**Comment by isuruf** [comment]
I've used the official source from openjdk.java.net
Ready for another review

**Comment by mingwandroid** [comment]
LGTM!

**Comment by isuruf** [comment]
Ping. I'd like to get this merged, so that I can install `openjdk` and `freetype` in the same env.

**Pull request merged**
