### PR TITLE
link libjvm.so

### PR DESCRIPTION
**Pull request by CJ-Wright**
link libjvm.so properly

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@conda-forge-admin please rerender

**Comment by CJ-Wright** [comment]
@conda-forge/openjdk @isuruf I think this is ready to go in as well. It does essentially the same thing as the PR into master just for java 8.

**Comment by xhochy** [comment]
@CJ-Wright What was the motivation for this? As mentioned in #66 this breaks `r-rjava` and actually this change is the reason for the issue. R uses `libjvm.so` as the proxy to find the general location of the java libraries: https://github.com/wch/r-source/blob/06185bd431beb9b6e0883193273d1779ef2c6a2c/src/scripts/javareconf.in#L204-L299

**Comment by CJ-Wright** [comment]
That was done for [jep](https://github.com/conda-forge/staged-recipes/pull/10694)

**Pull request merged**
