### PR TITLE
ENH add arch

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by xhochy** [comment]
cc @jayfurmanek Can you have a look at this? It seems like the Zuul build is for `ppc64be`, not `ppc64le`.

**Comment by jayfurmanek** [comment]
yeah, it looks like azul only offers ppc64 (Big Endien) builds, not ppc64le ones.
https://www.azul.com/downloads/zulu-community/?os=linux&package=jdk

adoptopenjdk.net has ppc64le builds:
https://adoptopenjdk.net/releases.html

Perhaps we should use that for ppc64le

**Comment by beckermr** [comment]
Yup. @jayfurmanek can you take a pass at that?

**Comment by jayfurmanek** [comment]
Sure. I'll take a look. 
Only for master/11? or for like java8 too?

**Comment by beckermr** [comment]
Master at 11 already works. We need 8 for r-rjava.

**Comment by jayfurmanek** [comment]
ah..right. I see this is the java8 branch. Okey doke.

**Comment by jayfurmanek** [comment]
It looks like `linux-64` uses AdoptJDK as well on the java11/master branch. Do we want to roll that change back to the java8 branch too to keep things consistent? Or should we not touch the `linux-64` arch and only add AdoptJDK for ppc and arm?
If we make it like the java11 branch, then we can re-use the build scripts from there as well.

**Comment by beckermr** [comment]
Whatever is easiest for you.

**Pull request closed without merging**
