### PR TITLE
Add JNI Test case

### PR DESCRIPTION
**Pull request by sodre**
The current recipe puts is copying the "include" headers under the wrong directory.
I am adding the test case for that, and will follow up with a fix soon.

### CODE REVIEW

**Comment by sodre** [comment]
@johanneskoester, I am not sure why the Windows build is not working, it seems that appveyor is acting up randomly. I will try to debug that as well.

**Comment by johanneskoester** [comment]
Thanks! I have no clue about windows. Maybe I was just lucky that it worked before.

**Comment by sodre** [comment]
@johanneskoester 
   I am done with the changes, feel free to merge once the build system catches up.

**Comment by johanneskoester** [comment]
Great work, thanks a lot!

**Pull request merged**
