### PR TITLE
Move libraries to /lib/jvm

### PR DESCRIPTION
**Pull request by Hoeze**
This PR fixes issues with colliding packages by moving the openjdk installation to `$CONDA_PREFIX/lib/jvm`, similar how other linux distributions do.
Solves e.g. https://github.com/conda-forge/openjdk-feedstock/issues/86

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Hoeze** [comment]
@conda-forge-admin, please rerender

**Comment by Hoeze** [comment]
@CJ-Wright, @izahn, @johanneskoester, @mingwandroid, @sodre, @xhochy:
This PR is ready and could be merged if you agree :)

**Comment by Hoeze** [comment]
@xhochy Kind push :)
Would you mind merging this PR to solve #86?

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
I'm thumbs-up on this, but I wish we had more comprehensive tests to make sure this doesn't break anything.

**Comment by xhochy** [comment]
I'm not 100% certain this works in all cases. I would love to test the interaction with `r-base`/ `r-rjava` first before merging. I know that I had issues in the past with them and JVM paths.

**Comment by Hoeze** [comment]
IMHO, if r-java would really have problems with reading JAVA_HOME, then this should be fixed in r-java.
It's a worse idea to keep the status-quo for a single downstream library as it (possibly) breaks a lot of other packages.

Anyways, how would one test this?
Is there some kind of conda-forge-testing channel one could use?

**Comment by Hoeze** [comment]
@xhochy Any way forward on this PR?

**Comment by izahn** [comment]
Yes, let's add a test for `rJava` and see what happens. Something like https://github.com/izahn/openjdk-feedstock/commit/02bd25d43b96e4cde4b902d6fe0bb8b4bc5a0801 should do it.

**Comment by Hoeze** [comment]
Alright, I created #104 to test your changes :)

**Comment by izahn** [comment]
@xhochy it looks like rJava is OK, tested in https://github.com/conda-forge/openjdk-feedstock/pull/104. Any other concerns?

**Review by izahn — APPROVED** [review]

**Comment by Hoeze** [comment]
Thanks a lot for reviewing and merging this PR @izahn @xhochy!

**Comment by christophfink** [comment]
Hi @Hoeze : Thanks for merging this. 

I noticed that OpenJDK 11 for Windows has not been rebuilt (or at least has not landed in conda-forge). 

It’s kinda important for us over at https://github.com/r5py/r5py - could you look into why the version was not rebuilt? Thanks!

**Comment by Hoeze** [comment]
Hi @christophfink, I created a PR to trigger a rebuild, lets see :)
https://github.com/conda-forge/openjdk-feedstock/pull/106

If this does not help, I'd suggest you to open an issue and ask for package maintainers' help.

**Comment by christophfink** [comment]
Thanks!

**Comment by mariusvniekerk** [comment]
Has this change been backported to openjdk11 as well?

**Comment by Hoeze** [comment]
@mariusvniekerk Yes, but I think it was not pushed to the conda-forge repo. See #106.
Some maintainer (@xhochy ?) would have to merge this to trigger the push to conda-forge.

**Comment by xhochy** [comment]
Done.

**Pull request merged**
