### PR TITLE
openjdk11: Revert libjvm linkage

### PR DESCRIPTION
**Pull request by xhochy**
Related to #66 

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
This is not the correct solution. We should fix `r-rjava`

**Comment by isuruf** [comment]
Can you add `file` to `yum_requirements.txt`?

**Comment by xhochy** [comment]
Seems like more things are missing but the error message is too cryptic for me.

**Comment by CJ-Wright** [comment]
@conda-forge-admin please rerender

**Pull request merged**
